export const YELLOW_IMG_TYPE = {
    pornographic: 1,
    hot: 2,
    normal: 3
};

export const pornographicThreshold = 83;

export const TAG_NAME = {
    normal: '正常',
    hot: '性感',
    porn: '色情'
};

export const TERROR_NAME_MAP = {
    terrorists: '武装恐怖分子',
    normalarmy: '武装非恐怖分子',
    knife: '刀',
    guns: '枪支',
    blood: '血液',
    fire: '火',
    flag: '旗帜',
    ship: '舰船',
    crowd: '人群',
    aircraft: '飞机',
    cannon: '火炮',
    armoredcar: '装甲车',
    other_weapon: '其他武器',
    other: '正常'
};

export const FIVE_HUNDRED_KB = 500 * 1024;
export const SEVEN_HUNDRED_KB = 700 * 1024;
export const ONE_MB = 1024 * 1024;

// 支持的文件类型
export const IMAGE_TYPE = [
    'jpg',
    'png',
    'jpeg'
];

export const ERRCODE = {
    OPENAPI_IMGFMT_INVALID: 16396, // 图片格式非法
    OPENAPI_IMGSIZE_TOOBIG: 16397, // 图片体积过大
    OPENAPI_IMGURL_INVALID: 16398, // 图片地址非法
    OPENAPI_IMGURL_COULDNTDOWNN: 16399, // 图片下载失败

    // 天天P图相关错误码
    OPENAPI_TTPT_NOFACE: 16402, // 待处理图片没有人脸

    OPENAPI_YOUTU_DISTANCE_ERROR: 16403, // 相似度错误
    OPENAPI_YOUTU_IMAGE_FACEDETECT_FAILED: 16404, // 人脸检测失败
    OPENAPI_YOUTU_IMAGE_DECODE_FAILED: 16405, // 图片解码失败
    OPENAPI_YOUTU_FEAT_PROCESSFAILED: 16406, // 特征处理失败
    OPENAPI_YOUTU_FACE_SHAPE_FAILED: 16407, // 提取轮廓错误
    OPENAPI_YOUTU_FACE_GENDER_FAILED: 16408, // 提取性别错误
    OPENAPI_YOUTU_FACE_EXPRESSION_FAILED: 16409, // 提取表情错误
    OPENAPI_YOUTU_FACE_AGE_FAILED: 16410, // 提取年龄错误
    OPENAPI_YOUTU_FACE_POSE_FAILED: 16411, // 提取姿态错误
    OPENAPI_YOUTU_FACE_GLASS_FAILED: 16412, // 提取眼镜错误
    OPENAPI_YOUTU_FACE_BEAUTY_FAILED: 16413, // 提取魅力值错误
    OPENAPI_YOUTU_TTS_PROCESS_FAILED: 16414, // 语音合成失败
    OPENAPI_YOUTU_ERROR_IMAGE_EMPTY: 16415, // 图片为空
    OPENAPI_YOUTU_ERROR_PERSON_EXISTED: 16416, // 个体已存在
    OPENAPI_YOUTU_ERROR_PERSON_NOT_EXISTED: 16417, // 个体不存在
    OPENAPI_YOUTU_ERROR_FACE_NOT_EXISTED: 16418, // 人脸不存在
    OPENAPI_YOUTU_ERROR_GROUP_NOT_EXISTED: 16419, // 组不存在
    OPENAPI_YOUTU_ERROR_GROUPLIST_NOT_EXISTED: 16420, // 组列表不存在
    OPENAPI_YOUTU_ERROR_FACE_NUM_EXCEED: 16421, // 人脸个数超过限制
    OPENAPI_YOUTU_ERROR_PERSON_NUM_EXCEED: 16422, // 个体个数超过限制
    OPENAPI_YOUTU_ERROR_GROUP_NUM_EXCEED: 16423, // 组个数超过限制
    OPENAPI_YOUTU_ERROR_SAME_FACE_ADDED: 16424, // 对个体添加了几乎相同的人脸
    OPENAPI_YOUTU_ERROR_IMAGE_FORMAT_INVALID: 16425, // 无效的图片格式
    OPENAPI_YOUTU_ERROR_IMAGE_FUZZY_DETECT_FAILED: 16426, // 图片模糊度检测失败
    OPENAPI_YOUTU_ERROR_IMAGE_FOOD_DETECT_FAILED: 16427, // 美食图片检测失败
    OPENAPI_YOUTU_ERROR_IMAGE_FINGERPRINT_FAILED: 16428, // 提取图像指纹失败
    OPENAPI_YOUTU_ERROR_IMAGE_COMPARE_FAILED: 16429 // 图像特征比对失败
};

export const ERRMSG = {
    [ERRCODE.OPENAPI_TTPT_NOFACE]: '检测不到人脸',
    [ERRCODE.OPENAPI_IMGFMT_INVALID]: '请上传JPG，PNG格式的图片',
    [ERRCODE.OPENAPI_IMGSIZE_TOOBIG]: '图片大小不能超过1M',
    [ERRCODE.OPENAPI_IMGURL_INVALID]: '非法URL地址',
    [ERRCODE.OPENAPI_IMGURL_COULDNTDOWNN]: '图片下载失败',
    [ERRCODE.OPENAPI_YOUTU_DISTANCE_ERROR]: '相似度错误',
    [ERRCODE.OPENAPI_YOUTU_IMAGE_FACEDETECT_FAILED]: '人脸检测失败',
    [ERRCODE.OPENAPI_YOUTU_IMAGE_DECODE_FAILED]: '图片解码失败',
    [ERRCODE.OPENAPI_YOUTU_FEAT_PROCESSFAILED]: '特征处理失败',
    [ERRCODE.OPENAPI_YOUTU_FACE_SHAPE_FAILED]: '提取轮廓错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_GENDER_FAILED]: '提取性别错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_EXPRESSION_FAILED]: '提取表情错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_AGE_FAILED]: '提取年龄错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_POSE_FAILED]: '提取姿态错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_GLASS_FAILED]: '提取眼镜错误',
    [ERRCODE.OPENAPI_YOUTU_FACE_BEAUTY_FAILED]: '提取魅力值错误',
    [ERRCODE.OPENAPI_YOUTU_TTS_PROCESS_FAILED]: '语音合成失败',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_EMPTY]: '图片为空',
    [ERRCODE.OPENAPI_YOUTU_ERROR_PERSON_EXISTED]: '个体已存在',
    [ERRCODE.OPENAPI_YOUTU_ERROR_PERSON_NOT_EXISTED]: '个体不存在',
    [ERRCODE.OPENAPI_YOUTU_ERROR_FACE_NOT_EXISTED]: '人脸不存在',
    [ERRCODE.OPENAPI_YOUTU_ERROR_GROUP_NOT_EXISTED]: '组不存在',
    [ERRCODE.OPENAPI_YOUTU_ERROR_GROUPLIST_NOT_EXISTED]: '组列表不存在',
    [ERRCODE.OPENAPI_YOUTU_ERROR_FACE_NUM_EXCEED]: '人脸个数超过限制',
    [ERRCODE.OPENAPI_YOUTU_ERROR_PERSON_NUM_EXCEED]: '个体个数超过限制',
    [ERRCODE.OPENAPI_YOUTU_ERROR_GROUP_NUM_EXCEED]: '组个数超过限制',
    [ERRCODE.OPENAPI_YOUTU_ERROR_SAME_FACE_ADDED]: '对个体添加了几乎相同的人脸',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_FORMAT_INVALID]: '无效的图片格式',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_FUZZY_DETECT_FAILED]: '图片模糊度检测失败',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_FOOD_DETECT_FAILED]: '美食图片检测失败',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_FINGERPRINT_FAILED]: '提取图像指纹失败',
    [ERRCODE.OPENAPI_YOUTU_ERROR_IMAGE_COMPARE_FAILED]: '图像特征比对失败'
};
